# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ rrs-kvalev-preview, rrs-kvalev-preview-testing, rrs-lastzero-kvalev-testing ]
  pull_request:
    branches: [ rrs-kvalev-preview, rrs-kvalev-preview-testing, rrs-lastzero-kvalev-testing ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Cache
        uses: actions/cache@v3

      - name: Create compose stack
        run: docker-compose -f docker-compose.ci.yml up -d --build --force-recreate

      - name: Compile and run tests
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism make all test install migrate

      - name: Tear down stack
        run: docker-compose -f docker-compose.ci.yml down
