name: Build and archive plugin solibs

on:
  push:
    branches: [ rrs-kvalev-preview, rrs-kvalev-preview-testing, rrs-lastzero-kvalev-testing ]
  pull_request:
    branches: [ rrs-kvalev-preview, rrs-kvalev-preview-testing, rrs-lastzero-kvalev-testing ]

  workflow_dispatch:
    branches: [ rrs-kvalev-preview, rrs-kvalev-preview-testing, rrs-lastzero-kvalev-testing ]

jobs:
  build-and-archive-plugins:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get Date
        id: get-date
        run: |
          echo "date=$(/bin/date -u "+%Y%m%d")" >> $GITHUB_OUTPUT
        shell: bash

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            plugins/
            storage/plugins/
            ~/.cache/docker-compose
          key: ${{ runner.os }}-${{ steps.get-date.outputs.date }}

      - name: Create compose stack
        run: docker-compose -f docker-compose.ci.yml up -d --build --force-recreate

      - name: Compile plugins
        id: compile_plugins
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism make build-plugins

      - name: Look for plugin solibs
        run: docker-compose -f docker-compose.ci.yml exec -T photoprism find storage/plugins/
        if: always() && steps.compile_plugins.outcome == 'success'

      - name: Copy plugins from container to host
        run: docker compose -f docker-compose.ci.yml cp photoprism:/go/src/github.com/photoprism/photoprism/storage/plugins/ plugins/
        if: always() && steps.compile_plugins.outcome == 'success'

      - name: Tear down stack
        run: docker-compose -f docker-compose.ci.yml down

      - name: Archive plugins
        uses: actions/upload-artifact@v3
        if: always() && steps.compile_plugins.outcome == 'success'
        continue-on-error: true
        with:
          name: plugins
          path: plugins/
