name: Build plugin docker images

on:
  pull_request:
    paths:
      - "ext/**"

jobs:
  publish-plugin-docker-images:
    strategy:
      fail-fast: false
      matrix:
        plugin:
          - name: realesrgan
            version: 0.3.0
          - name: yolo8
            version: 8.0.110

    runs-on: ubuntu-latest
    steps:
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            changed: 'ext/${{ matrix.plugin.name }}/**'

      - name: Checkout
        if: steps.changes.outputs.changed == 'true'
        uses: actions/checkout@v3

      - name: Cache
        if: steps.changes.outputs.changed == 'true'
        uses: actions/cache@v3

      - name: Log in to Docker Hub
        if: steps.changes.outputs.changed == 'true'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        if: steps.changes.outputs.changed == 'true'
        uses: docker/build-push-action@v2
        with:
          context: ext/${{ matrix.plugin.name }}
          tags: kvalev/${{ matrix.plugin.name }}:${{ matrix.plugin.version }}
          push: true
